name: stereo_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.1
  - torchvision=0.16.1
  - numpy
  - opencv
  - matplotlib
  - tensorboard
  - tqdm
  - pip
  - pip:
    - Pillow>=9.0.0
    - gradio==4.29.0
    - gradio-imageslider
